// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmgshjywmcpdzgakueyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtZ3Noanl3bWNwZHpnYWt1ZXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTcyMzksImV4cCI6MjA2NjE3MzIzOX0.4sOvFJtCjCUUg58GA-NixEF817Hl6zZxr3lFSPdilVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);